version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: tpcds_postgres
    environment:
      POSTGRES_USER: tpcds
      POSTGRES_PASSWORD: tpcds_password
      POSTGRES_DB: tpcds
    ports:
      - "5432:5432"
    volumes:
      - ./tpcds_data_1:/data
      - ./tpcds-kit/tools/tpcds.sql:/sql/tpcds.sql
      - ./load_data.sql:/sql/load_data.sql
      - ./create_inmon_ddl.sql:/sql/create_inmon_ddl.sql
      - ./create_inmon_etl.sql:/sql/create_inmon_etl.sql
      - ./dv_ddl.sql:/sql/dv_ddl.sql
      - ./dv_etl.sql:/sql/dv_etl.sql
